### ISSUE TITLE
BLE Driver

### ISSUE THREAD

**Issue by sleeplessmisty** [Ltu-Bike-trailer/control-software#6]
This is done when the ESP32C3 unit is able to broadcast itself over BLE, send relevant data to the app and store logs of its state.

**To reach this there are subtasks that need to be done:**
- [x] Create a broadcast and connection module for the ESP32C3 so smartphones can find and connect to it
- [x] Look into using the same protocol as the system to retrieve and send data to smartphone via BLE
- [x] Create a module for streaming fake data for testing purposes

**Comment by ivajon** [comment]
Are we ready to merge this?

**Comment by sleeplessmisty** [comment]
Ready to be merged, but will wait until CAN is fixed on it aswell
